#### 1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [9]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

x = np.array(zp, dtype=np.float64)
y = np.array(ks, dtype=np.float64)

In [10]:
import numpy as np
b = (np.mean(x * y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x) ** 2)
b

2.620538882402765

In [11]:
a = np.mean(y) - b * np.mean(x)
a

444.1773573243596

In [20]:
y_hat = 444.18+2.62*x
y_hat

array([[535.88],
       [562.08],
       [941.98],
       [968.18],
       [548.98],
       [627.58],
       [585.66],
       [837.18],
       [758.58],
       [732.38]])

In [21]:
y

array([[401.],
       [574.],
       [874.],
       [919.],
       [459.],
       [739.],
       [653.],
       [902.],
       [746.],
       [832.]])

без  intercept

In [16]:
x = x.reshape((10,1))
x

array([[ 35.],
       [ 45.],
       [190.],
       [200.],
       [ 40.],
       [ 70.],
       [ 54.],
       [150.],
       [120.],
       [110.]])

In [17]:
y = y.reshape((10,1))
y

array([[401.],
       [574.],
       [874.],
       [919.],
       [459.],
       [739.],
       [653.],
       [902.],
       [746.],
       [832.]])

In [18]:
b = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T @ y)
b

array([[5.88982042]])

#### 2.Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [24]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

X = np.array(zp, dtype=np.float64)
y = np.array(ks, dtype=np.float64)

In [28]:
def mse_ (B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

alpha = 1e-6
B1 = 0.1
n = 10

    

In [29]:
for i in range(3000):
    B1 -= alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%50 == 0:
        print(f'Iteration: {i}, B1= {B1}, mse = {mse_(B1)}')

Iteration: 0, B1= 0.25952808, mse = 493237.7212546963
Iteration: 50, B1= 4.497229618367758, mse = 83233.94472982832
Iteration: 100, B1= 5.54537842245223, mse = 58151.31823171113
Iteration: 150, B1= 5.804626485478126, mse = 56616.849068093856
Iteration: 200, B1= 5.868748638669329, mse = 56522.97550129376
Iteration: 250, B1= 5.884608547059329, mse = 56517.232638059555
Iteration: 300, B1= 5.888531320728348, mse = 56516.88130936019
Iteration: 350, B1= 5.889501575592372, mse = 56516.85981627392
Iteration: 400, B1= 5.8897415574471985, mse = 56516.85850140053
Iteration: 450, B1= 5.889800914315978, mse = 56516.858420961085
Iteration: 500, B1= 5.889815595583751, mse = 56516.858416040064
Iteration: 550, B1= 5.889819226833643, mse = 56516.858415739014
Iteration: 600, B1= 5.889820124983314, mse = 56516.85841572062
Iteration: 650, B1= 5.889820347130743, mse = 56516.858415719485
Iteration: 700, B1= 5.889820402076462, mse = 56516.85841571941
Iteration: 750, B1= 5.889820415666681, mse = 56516.85841571

#### B1= 5.89

In [31]:
y_hat = 5.89*X
y_hat

array([ 206.15,  265.05, 1119.1 , 1178.  ,  235.6 ,  412.3 ,  318.06,
        883.5 ,  706.8 ,  647.9 ])